name: CI-BETA

on:
  push:
    branches:
      - beta
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          NODE_ENV: beta
      - name: Archive Static-Dist
        uses: actions/upload-artifact@master
        with:
          name: .next
          path: .next
  deploy:
    name: Deploy Beta
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: .next
          path: .next
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:beta
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
